In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/home/roni/Downloads/department_store_inventory_v5.csv')

In [3]:
df

,Store_ID,Store_Name,Category,Product_ID,Product_Name,SKU,Price,Stock_Level,Last_Updated
0,S001,Top11,의류,P0001,은하수 린넨 셔츠 (Small),FSH-GALAXY_SHR-S-619,82400,0,2025-12-13 19:21:43
1,S001,Top11,의류,P0002,은하수 린넨 셔츠 (Medium),FSH-GALAXY_SHR-M-136,82400,0,2026-01-14 15:28:06
2,S001,Top11,의류,P0003,은하수 린넨 셔츠 (Large),FSH-GALAXY_SHR-L-929,82400,0,2025-09-03 08:32:38
3,S001,Top11,의류,P0004,새벽 안개 슬랙스 (Small),FSH-MIST_PNT-S-585,95700,0,2025-08-12 05:48:43
4,S001,Top11,의류,P0005,새벽 안개 슬랙스 (Medium),FSH-MIST_PNT-M-518,95700,0,2025-10-04 00:57:38
...,...,...,...,...,...,...,...,...,...
95,S010,골든 듀드,액세서리,P0096,우주 궤도 뱅글,ACC-ORB_BGL-5528,388300,0,2025-10-05 10:25:16
96,S010,골든 듀드,액세서리,P0097,영원한 약속 커플링,ACC-EVR_CPR-5056,1454000,0,2025-11-01 10:07:46
97,S010,골든 듀드,액세서리,P0098,보석함 속 비밀,ACC-SEC_BOX-2227,52600,0,2025-12-07 14:30:49
98,S010,골든 듀드,액세서리,P0099,숲의 요정 브로치,ACC-FRT_BRH-3276,190400,0,2025-10-10 03:37:30
99,S010,골든 듀드,액세서리,P0100,바다의 심장 발찌,ACC-SEA_ANK-4693,129600,0,2026-01-16 10:43:07

In [4]:
df.drop('Store_ID', axis = 1, inplace = True)

In [5]:
df_store = df[['Store_Name','Category']]

In [6]:
df_store['poi_id'] = 0

In [7]:
df_store

   Store_Name Category  poi_id
0       Top11       의류       0
1       Top11       의류       0
2       Top11       의류       0
3       Top11       의류       0
4       Top11       의류       0
..        ...      ...     ...
95      골든 듀드     액세서리       0
96      골든 듀드     액세서리       0
97      골든 듀드     액세서리       0
98      골든 듀드     액세서리       0
99      골든 듀드     액세서리       0

[100 rows x 3 columns]

In [8]:
df_store.rename(columns={'Store_Name': 'name', 'Category': 'category'}, inplace=True)

In [9]:
df_store.drop_duplicates(subset=['name'],inplace = True)

In [11]:
df_store.loc[df_store['category'] == '의류', 'category'] = 'fashion'
df_store.loc[df_store['category'] == '뷰티', 'category'] = 'cosmetic'
df_store.loc[df_store['category'] == '잡화', 'category'] = 'shoes'
df_store.loc[df_store['category'] == '키즈', 'category'] = 'kids'
df_store.loc[df_store['category'] == '아웃도어', 'category'] = 'outdoor'
df_store.loc[df_store['category'] == '가전', 'category'] = 'electric'
df_store.loc[df_store['category'] == '리빙', 'category'] = 'living'
df_store.loc[df_store['category'] == '액세서리', 'category'] = 'jewelry'

In [12]:
df_store

              name  category  poi_id
0            Top11   fashion       0
10  Christian Tior   fashion       0
20       7 Seconds   fashion       0
30           오렌지 영  cosmetic       0
40          XYZ 마트     shoes       0
50           토이 시티      kids       0
60         노스 페이스업   outdoor       0
70         하이 마트박스  electric       0
80             한샘플    living       0
90           골든 듀드   jewelry       0

In [127]:
df_store.to_csv('/home/roni/Downloads/store_db.csv', index = False)

In [128]:
df_product = df[['Product_Name','SKU', 'Price']]

In [129]:
df_product.rename(columns = {'Product_Name':'name', 'SKU':'sku', 'Price':'price'})

                  name                   sku    price
0    은하수 린넨 셔츠 (Small)  FSH-GALAXY_SHR-S-619    82400
1   은하수 린넨 셔츠 (Medium)  FSH-GALAXY_SHR-M-136    82400
2    은하수 린넨 셔츠 (Large)  FSH-GALAXY_SHR-L-929    82400
3    새벽 안개 슬랙스 (Small)    FSH-MIST_PNT-S-585    95700
4   새벽 안개 슬랙스 (Medium)    FSH-MIST_PNT-M-518    95700
..                 ...                   ...      ...
95            우주 궤도 뱅글      ACC-ORB_BGL-5528   388300
96          영원한 약속 커플링      ACC-EVR_CPR-5056  1454000
97            보석함 속 비밀      ACC-SEC_BOX-2227    52600
98           숲의 요정 브로치      ACC-FRT_BRH-3276   190400
99           바다의 심장 발찌      ACC-SEA_ANK-4693   129600

[100 rows x 3 columns]

In [134]:
df_product.rename(columns = {'Product_Name':'name', 'SKU':'sku', 'Price':'price'},
                  inplace=True)

In [135]:
df_product

                  name                   sku    price
0    은하수 린넨 셔츠 (Small)  FSH-GALAXY_SHR-S-619    82400
1   은하수 린넨 셔츠 (Medium)  FSH-GALAXY_SHR-M-136    82400
2    은하수 린넨 셔츠 (Large)  FSH-GALAXY_SHR-L-929    82400
3    새벽 안개 슬랙스 (Small)    FSH-MIST_PNT-S-585    95700
4   새벽 안개 슬랙스 (Medium)    FSH-MIST_PNT-M-518    95700
..                 ...                   ...      ...
95            우주 궤도 뱅글      ACC-ORB_BGL-5528   388300
96          영원한 약속 커플링      ACC-EVR_CPR-5056  1454000
97            보석함 속 비밀      ACC-SEC_BOX-2227    52600
98           숲의 요정 브로치      ACC-FRT_BRH-3276   190400
99           바다의 심장 발찌      ACC-SEA_ANK-4693   129600

[100 rows x 3 columns]

In [136]:
df_product.to_csv('/home/roni/Downloads/product_db.csv', index = False)

In [14]:
list(df_store.name)

['Top11',
 'Christian Tior',
 '7 Seconds',
 '오렌지 영',
 'XYZ 마트',
 '토이 시티',
 '노스 페이스업',
 '하이 마트박스',
 '한샘플',
 '골든 듀드']

In [21]:
data = {
    'name':[
            'robot_station_1',
            'robot_station_2',
            'robot_station_3',
            'charge_station_1',
            'charge_station_2',
            'charge_station_3',
            'charge_station_4',
            'charge_station_5',
            'maintenance_1',
            'cafe_1',
            'pickup_table_1',
            'fountain_1',
            'launge_area_1',
            'plant1',
            'pop_up_1',
            'vender_1',
            'F&B_zone_1',
            'Top11',
            'Christian Tior',
            '7 Seconds',
            '오렌지 영',
            'XYZ 마트',
            '토이 시티',
            '노스 페이스업',
            '하이 마트박스',
            '한샘플',
            '골든 듀드'
        ],
    'kind':['station', 
            'station',
            'station',
            'charger',
            'charger',
            'charger',
            'charger',
            'charger',
            'facility',
            'store',
            'pickup_table',
            'facility',
            'facility',
            'facility',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store',
            'store']
}

In [22]:
len(data['name'])

27

In [23]:
len(data['kind'])

27

In [24]:
df_pois = pd.DataFrame(data)

In [25]:
df_pois

                name          kind
0    robot_station_1       station
1    robot_station_2       station
2    robot_station_3       station
3   charge_station_1       charger
4   charge_station_2       charger
5   charge_station_3       charger
6   charge_station_4       charger
7   charge_station_5       charger
8      maintenance_1      facility
9             cafe_1         store
10    pickup_table_1  pickup_table
11        fountain_1      facility
12     launge_area_1      facility
13            plant1      facility
14          pop_up_1         store
15          vender_1         store
16        F&B_zone_1         store
17             Top11         store
18    Christian Tior         store
19         7 Seconds         store
20             오렌지 영         store
21            XYZ 마트         store
22             토이 시티         store
23           노스 페이스업         store
24           하이 마트박스         store
25               한샘플         store
26             골든 듀드         store

In [26]:
df_pois[['x_m','y_m']] = 0.0

In [28]:
df_pois[['wait_x_m', 'wait_y_m']] = 0.0

In [29]:
df_pois['arrival_confirm'] = 'NAV2'

In [32]:
import datetime

In [36]:
df_pois['create_at'] = pd.to_datetime('2024-01-01 00:00:00')

In [37]:
df_pois

,name,kind,x_m,y_m,wait_x_m,wait_y_m,arrival_confirm,create_at
0,robot_station_1,station,0.0,0.0,0.0,0.0,NAV2,2024-01-01
1,robot_station_2,station,0.0,0.0,0.0,0.0,NAV2,2024-01-01
2,robot_station_3,station,0.0,0.0,0.0,0.0,NAV2,2024-01-01
3,charge_station_1,charger,0.0,0.0,0.0,0.0,NAV2,2024-01-01
4,charge_station_2,charger,0.0,0.0,0.0,0.0,NAV2,2024-01-01
5,charge_station_3,charger,0.0,0.0,0.0,0.0,NAV2,2024-01-01
6,charge_station_4,charger,0.0,0.0,0.0,0.0,NAV2,2024-01-01
7,charge_station_5,charger,0.0,0.0,0.0,0.0,NAV2,2024-01-01
8,maintenance_1,facility,0.0,0.0,0.0,0.0,NAV2,2024-01-01
9,cafe_1,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
10,pickup_table_1,pickup_table,0.0,0.0,0.0,0.0,NAV2,2024-01-01
11,fountain_1,facility,0.0,0.0,0.0,0.0,NAV2,2024-01-01
12,launge_area_1,facility,0.0,0.0,0.0,0.0,NAV2,2024-01-01
13,plant1,facility,0.0,0.0,0.0,0.0,NAV2,2024-01-01
14,pop_up_1,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
15,vender_1,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
16,F&B_zone_1,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
17,Top11,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
18,Christian Tior,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
19,7 Seconds,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
20,오렌지 영,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
21,XYZ 마트,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
22,토이 시티,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
23,노스 페이스업,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
24,하이 마트박스,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
25,한샘플,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01
26,골든 듀드,store,0.0,0.0,0.0,0.0,NAV2,2024-01-01

In [38]:
df_pois.to_csv('/home/roni/Downloads/pois_db.csv', index = False)